### ISSUE TITLE
Remove Github Action Workflow checkout token ${{secrets.SUBMOD_PAT}}

### ISSUE THREAD

**Issue by medgar-nitric** [nitrictech/python-sdk#35]
To enable Github security dependency analysis feature 'Dependabot' we need to remove the Github secrets tokens so Dependabot can run when making a PR with updated dependencies.

```
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{secrets.SUB_MODULE_PAT}}
        submodules: recursive
```

https://github.com/nitrictech/python-sdk/blob/main/.github/workflows/test.yaml

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1dynndd) by [Unito](https://www.unito.io)
